version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
  - package-ecosystem: cargo
    directory: /crates/witness-component
    schedule:
      interval: weekly
    labels:
      - dependencies
  - package-ecosystem: cargo
    directory: /crates/witness-core
    schedule:
      interval: weekly
    labels:
      - dependencies
  - package-ecosystem: cargo
    directory: /crates/witness-mcdc-checker
    schedule:
      interval: weekly
    labels:
      - dependencies
  - package-ecosystem: cargo
    directory: /crates/witness-viz
    schedule:
      interval: weekly
    labels:
      - dependencies
  - package-ecosystem: npm
    directory: /tests/playwright
    schedule:
      interval: weekly
    labels:
      - dependencies
